.\" Written by Vincent Batts <vbatts@hashbangbash.com>
.TH SLACK-UTILS 3 "March 2011" "Slackware-Linux"
.SH NAME
slack-utils - Ruby library for harnessing Slackware Linux stuff

.SH SYNOPSIS
.LP
.B require 'slackare'

.SH DESCRIPTION
For more information on this library and its offerings,
use the `ri` command for "Slackare"
.br
.SS Example:
.I
$> ri Slackware


.SH "SEE ALSO"
.BR slack-utils(8)
.BR ruby(1)
.BR ri(1)
