.\" Written by Vincent Batts <vbatts@hashbangbash.com>
.TH SLACK-UTILS 8 "July 2010" "slackware-13.1"
.SH NAME
.B slack-utils - simple slackware sys-admin tools

.SH SYNOPSIS
.B  slp [string] ...
.LP
.B  slf [string] ...
.LP
.B  slt [string] ...
.LP
.B  sll [string] ...
.LP
.B  slo [string] ...
.LP

.SH DESCRIPTION
.B slack-utils
is mostly a simple chunk of ruby code (rest is bash shell) to produce 

.SH OPTIONS
